export const LISTINGS_REQUEST = 'LISTINGS_REQUEST';
export const LISTINGS_SUCCESS = 'LISTINGS_SUCCESS';
export const LISTINGS_FAIL = 'LISTINGS_FAIL';

export const LISTING_DETAILS_REQUEST = 'LISTINGS_DETAILS_REQUEST';
export const LISTING_DETAILS_SUCCESS = 'LISTINGS_DETAILS_SUCCESS';
export const LISTING_DETAILS_FAIL = 'LISTINGS_DETAILS_FAIL';